spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securitythree
    username: root
    password: 0910886381018
  main:
    allow-circular-references: true
  jpa :
    database-platform : org.springframework.orm.jpa.vendor.Database.MYSQL
    generate-ddl : true
    show-sql : true
    hibernate :
      ddl-auto : update
    properties :
      hibernate :
        globally_quoted_identifiers : true
        dialect : org.hibernate.dialect.MySQLDialect
        format_sql : true
logging:
  level:
    org.springframework.security: trace
aaron:
  app:
    secret: aaronSecretKey
    jwtExpiryDate: 86400000



